In [2]:
# Regularization
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("C:\\Users\\Eddie\\Downloads\\UNZIP_FOR_NOTEBOOKS_FINAL\\08-Linear-Regression-Models\\Advertising.csv")

In [4]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
X = df.drop('sales', axis = 1)

In [6]:
y = df['sales']

In [7]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
poly_converter = PolynomialFeatures(degree = 3, include_bias = False)

In [9]:
poly_features = poly_converter.fit_transform(X)

In [10]:
poly_features.shape

(200, 19)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
X_train = scaler.transform(X_train)

In [17]:
X_test = scaler.transform(X_test)

In [18]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [19]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [20]:
# RIDGE REGRESSION
from sklearn.linear_model import Ridge

In [21]:
ridge_model = Ridge(alpha = 10)

In [22]:
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [23]:
test_predictions = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test, test_predictions)

In [26]:
MAE

0.5774404204714183

In [27]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [28]:
RMSE

0.8946386461319686

In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
ridge_cv_model = RidgeCV(alphas = (0.1,1.0, 10.0), scoring = 'neg_mean_squared_error')

In [31]:
ridge_cv_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_squared_error')

In [32]:
ridge_cv_model.alpha_
# returns the best performing 

0.1

In [33]:
from sklearn.metrics import SCORERS

In [34]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [35]:
test_predictions = ridge_cv_model.predict(X_test)

In [36]:
MAE = mean_absolute_error(y_test, test_predictions)

In [37]:
MAE

0.42737748843373746

In [38]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [39]:
RMSE

0.6180719926921404

In [40]:
# Lasso Regression  - Least Absolute Shrinkage and Selection Operator

In [41]:
from sklearn.linear_model import LassoCV

In [47]:
lasso_cv_model = LassoCV(eps = 0.1, n_alphas=100,cv=5 )
# if error occurs on model fit because it does not converage up the max iterations -- max_iter
# alternatively you can lower the epsilon 

In [48]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [49]:
lasso_cv_model.alpha_

0.4943070909225828

In [51]:
test_predictions = lasso_cv_model.predict(X_test)

In [52]:
MAE = mean_absolute_error(y_test, test_predictions)

In [53]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [54]:
MAE

0.6541723161252854

In [55]:
RMSE

1.130800102276253

In [58]:
lasso_cv_model.coef_
# while the error rate is higher than RidgeCV 
# this model is also considerably less complex

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [59]:
lasso_cv_model2 = LassoCV(eps = 0.001, n_alphas=100,cv=5, max_iter = 1000000 )


In [60]:
lasso_cv_model2.fit(X_train,y_train)

LassoCV(cv=5, max_iter=1000000)

In [61]:
lasso_cv_model2.alpha_

0.004943070909225827

In [62]:
test_predictions = lasso_cv_model2.predict(X_test)

In [63]:
MAE = mean_absolute_error(y_test, test_predictions)

In [64]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [65]:
MAE

0.43350346185900673

In [66]:
RMSE

0.6063140748984039

In [68]:
lasso_cv_model2.coef_
# With higher number of iterations and lower epsilon 
# we get better results than previously with ridgeCV
# also we now consider more coefficients but still less than ridgeCV

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [69]:
# Elastic Net - Combining Lasso and Ridge

In [71]:
from sklearn.linear_model import ElasticNetCV

In [74]:
elastic_model = ElasticNetCV(l1_ratio = [.1,.5,.7,.9,.95,.99,1], eps = 0.001, n_alphas=100, max_iter = 1000000)

In [75]:
elastic_model.fit(X_train, y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [76]:
elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1]

In [77]:
elastic_model.l1_ratio_

1.0

In [78]:
elastic_model.alpha_

0.004943070909225827

In [79]:
test_predictions = elastic_model.predict(X_test)

In [80]:
MAE = mean_absolute_error(y_test, test_predictions)

In [81]:
MAE

0.43350346185900673

In [82]:
# same result as our previous lassoCV test
# essentially elastic model is saying lasso is the best fit for the data